# Route pour récupérer toutes les transactions pour le mois en cours, groupées par compte
  /transactions:
    get:
      tags:
        - Transactions Module
      summary: Get transactions by account for the current month
      description: API to fetch all transactions for the current month, grouped by account.
      parameters:
        - in: query
          name: accountId
          description: The ID of the account for which the transactions are requested
          required: true
          type: string
      responses:
        '200':
          description: Successfully fetched transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Invalid account ID or missing parameters
        '500':
          description: Internal Server Error
# Route pour récupérer les détails d'une transaction spécifique
  /transactions/{transactionId}:
    get:
      tags:
        - Transactions Module
      summary: Get details of a specific transaction
      description: API to fetch detailed information of a specific transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          description: The ID of the transaction to fetch details for
          type: string
      responses:
        '200':
          description: Successfully fetched transaction details
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
# Route pour mettre à jour une transaction (uniquement modifier, pas ajouter ou supprimer)          
    put:
      tags:
        - Transactions Module
      summary: Update an existing transaction
      description: API to update transaction details (like category, amount, description).
      parameters:
        - in: path
          name: transactionId
          required: true
          description: The ID of the transaction to update
          type: string
        - in: body
          name: body
          description: New details for the transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      responses:
        '200':
          description: Successfully updated transaction
        '400':
          description: Invalid request data or invalid transaction ID
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
